---
- name: Setup Storagenode Log Exporter (local), without exposing Port
  docker_container:
    container_default_behavior: compatibility
    networks_cli_compatible: no
    state: "{{ item.state | default('started') }}"
    restart_policy: unless-stopped
    name: "storj-log-exporter-{{ item.name }}"
    image: kevinkk525/storj-log-exporter:latest
    memory: 50M
    networks:
      - name: "{{ storj_network_name }}"
    mounts:
      - type: bind
        source: "{{ item.path }}/data"
        target: /app/logs
    user: 1000:1000
    command: "-config /app/config.yml"
  with_items:
    - "{{ storj_nodes }}"
  when: item.vpn_client is undefined and item.ext_port_log_exporter is undefined

- name: Setup Storagenode Log Exporter (local), exposing Port
  docker_container:
    container_default_behavior: compatibility
    networks_cli_compatible: no
    state: "{{ item.state | default('started') }}"
    restart_policy: unless-stopped
    name: "storj-log-exporter-{{ item.name }}"
    image: kevinkk525/storj-log-exporter:latest
    memory: 50M
    published_ports:
      - "{{ item.ext_port_exporter }}:9651"
    networks:
      - name: "{{ storj_network_name }}"
    mounts:
      - type: bind
        source: "{{ item.path }}/data"
        target: /app/logs
    user: 1000:1000
    command: "-config /app/config.yml"
  with_items:
    - "{{ storj_nodes }}"
  when: item.vpn_client is undefined and item.ext_port_log_exporter is defined

- name: Setup Storagenode Log exporter (via VPN)
  docker_container:
    container_default_behavior: compatibility
    networks_cli_compatible: no
    state: "{{ item.state | default('started') }}"
    restart_policy: unless-stopped
    name: "storj-log-exporter-{{ item.name }}"
    image: kevinkk525/storj-log-exporter:latest
    memory: 50M
    networks:
      - name: "{{ storj_network_name }}"
    links: "vpn-{{ item.vpn_client }}:storj-{{ item.name }}"
    mounts:
      - type: bind
        source: "{{ item.path }}/data"
        target: /app/logs
    user: 1000:1000
    command: "-config /app/config.yml"
  with_items:
    - "{{ storj_nodes }}"
  when: item.vpn_client is defined

